### ISSUE TITLE
input reference file is missing

### ISSUE THREAD

**Issue by proukakis** [tobiasrausch/alfred#11]
Hi, I am trying to run this via docker on a mac El Capitan OS (couldn't build from source or find a mac version on Conda)

docker run trausch/alfred alfred qc -r /Volumes/Toshiba4Tb/GenomeReferences/hg38.fa -j qc.json.gz /Volumes/Toshiba4Tb/single_cell_data/67_10.picoplex.qs.oct18/bam/D38-7-S2.67_10.qiascout.picoplex.samblasted.sorted.bam

Input reference file is missing: /Volumes/Toshiba4Tb/GenomeReferences/hg38.fa

I have tried different directories with the same reference, and get the same result

Is there an obvious thing I am missing?

thanks
christos

**Comment by tobiasrausch** [comment]
Delly should compile using Mac OS but you need to install boost first using brew (https://brew.sh/) with `brew install boost`

The docker version contains alfred but that means you need to mount all your data directories in the container otherwise alfred is not finding the files. The option you need to look at is:

`docker run -v ~/myHostDir:/var/log/insideContainerDir ...`

Does this work?

**Comment by proukakis** [comment]
Yes it works after upgrading boost and rerunning make, many thanks!

Sorry, had forgotten all the business about mounting on docker (which is why i try to avoid it...)

PS Alfred, not Delly!

**Comment by proukakis** [comment]
Yes it works after upgrading boost and rerunning make, many thanks!

Sorry, had forgotten all the business about mounting on docker (which is why i try to avoid it...)

PS Alfred, not Delly!
