### ISSUE TITLE
 unrecognised option '-f' with docker image

### ISSUE THREAD

**Issue by Rhinogradentia** [tobiasrausch/alfred#23]
Hi,

trying to create a json output according the usage guide but with the docker image with this command:
 `docker run -v /tmp/myDir:/tmp trausch/alfred alfred qc -f json -r /tmp/genome.fa -o /tmp/qc.json.gz /tmp/sorted.bam`

Is works fine without the -f parameter. 

Additionally, I was trying to run the R-Script from the docker container and couldn't get this working either. How would I have to call this?

Thank you,
Best,
Nadine

**Comment by tobiasrausch** [comment]
Hi,

Sorry, we forgot to update the documentation. The '-f' parameter is deprecated, alfred always outputs json and tsv now.

`docker run -v /tmp/myDir:/tmp/ trausch/alfred alfred qc -r /tmp/genome.fa -j /tmp/qc.json.gz -o /tmp/qc.tsv.gz /tmp/sorted.bam`

The Rscript is indeed not included in the container because installing R and all the dependencies makes the container quite large in size. Since alfred outputs a JSON file, you can simply upload this JSON file to [https://www.gear-genomics.com/alfred/](https://www.gear-genomics.com/alfred/) for interactive browsing of the QC metrics. 

Best, Tobias

**Comment by Rhinogradentia** [comment]
Thanks! I' used the R-Scripts directly from the git repo for the tsv file - this worked fine.
Best, 
Nadine
